# Generated by Django 5.2.7 on 2025-10-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(unique=True)),
                ('cor', models.CharField(default='#000000')),
            ],
        ),
        migrations.AddField(
            model_name='tarefa',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, to='tarefas.etiqueta'),
        ),
    ]
