# Generated by Django 5.2.7 on 2025-10-30 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0004_etiqueta_tarefa_etiquetas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarefa',
            options={'permissions': [('can_view_all_tarefas', 'Can view tasks from all users')]},
        ),
    ]
